apiVersion: autoscaling.x-k8s.io/v1alpha1
kind: StartupCPUBoost
metadata:
  labels:
    app.kubernetes.io/name: startupcpuboost
    app.kubernetes.io/instance: startupcpuboost-sample
    app.kubernetes.io/part-of: kube-startup-cpu-boost
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kube-startup-cpu-boost
  name: startupcpuboost-sample
spec:
  # TODO(user): Add fields here
